---
title: "Plotting FIPS and Variables"
author: "Isabel Lopez"
date: "9/7/2021"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
suppressPackageStartupMessages({
library(tidyverse)
library(tidycensus)
library(here)
library(ggthemes)
library(lubridate)  
})  
```

```{r define_target_parameters}

all_targetdata <- readRDS(file = here("data","all_targetdata.RDS")) 
  all_targetdata[all_targetdata == 0]<- NA 
 all_targetdata2<- na.omit(all_targetdata)
 # targethurdat1[targethurdat = NA]
 # targethurdat1 <- filter(targethurdat1, !is.na(ss))
 # anyNA(targethurdat1$ss)
  targethurdat150 <- filter(targethurdat150, !is.na(ss))
 anyNA(targethurdat150$ss)

targetcoastal_fips <-readRDS(file = here("data","targetcoastal_FIPS.RDS"))
fips <- targetcoastal_fips$fips
texas_fips<- c('48007','48039','48057',
             '48061','48071','48167','48201','48239','48245',
             '48261','48273','48321','48355','48361','48391',
             '48409','48469','48489')

florida_fips <- c ('12005','12009','12011','12015','12017','12019',
             '12021','12029','12031','12033','12035','12037',
             '12045','12053','12057','12061','12065','12071',
             '12075','12077','12081','12085','12086','12087',
             '12089','12091','12099','12101','12103','12107',
             '12109','12111','12113','12115','12123','12127',
             '12129','12131')
northcarolina_fips<- c('37013','37015','37019','37029','37031',
             '37041','37049','37053','37055','37073','37091',
             '37095','37103','37129','37133','37137','37139',
             '37141','37143','37147','37177','137187')
louisiana_fips<-c('22005','22007','22019','22023',
             '22045','22051','22053','22057','22063','22071',
             '22075','22087','22089','22093','22095','22099',
             '22101','22103','22105','22109','22113')


```
```{r wrangle-data}

# target_sicindustry_codes<-c('SIC_0G','SIC_0G53','SIC_0G58','SIC_0I70','SIC_0I79','SIC_0D20',
#                            'SIC_0D23','SIC_0G56','SIC_0G59')
# 
# Leisure_Hospitality <- c('1026','72')

target_sicindustry_codes<-c('SIC_0G', 'SIC_0G54','SIC_0F51', 'SIC_0D39', 'SIC_0I79','SIC_0I73')


target_naics_industry_codes <- c('44-45', '72', '42', '1013', '1026', '1024')

vars <-c("qtrly_estabs_count","month1_emplvl","month2_emplvl","month3_emplvl","avg_wkly_wage")


 

# 
# all_targetdata2[all_targetdata2 == "1026 Leisure and Hospitality" ] <- "Leisure and Hospitality" 
# all_targetdata2[all_targetdata2 == "NAICS 72 Accomodation and foods services" ] <- "Accomodation and foods services"
all_targetdata3 <- all_targetdata2 %>% 
  mutate(industry_title = ifelse (grepl("hospitality", industry_title),
                                  "Leisure and hospitality" , industry_title),
        industry_title = ifelse (trimws(industry_title) == "NAICS 72 Accommodation and food services",
                                  "Accommodation and food services" , industry_title),
        industry_title = ifelse (trimws(industry_title) == "NAICS 44-45 Retail Trade",
                              "Retail trade", industry_title),
        industry_title = ifelse (trimws(industry_title) == "NAICS 42 Wholesale trade",
                              "Wholesale trade", industry_title),
        industry_title = ifelse (trimws(industry_title) == "1013 Manufacturing",
                              "Manufacturing", industry_title),
         industry_title = ifelse (trimws(industry_title) == "1024 Professional and business services",
                              "Professional and business service", industry_title),
        
        time = yq(sprintf("%4d: Q%d",year, qtr)))
        # time = year + ((qtr*3)-1)/12 )

# all_leisuredata3[all_leisuredata3 == '1026 Leisure and Hospitality'] <- "Leisure and Hospitality"
# all_leisuredata <- all_targetdata %>% all_leisuredata3<- all_targetdata2 %>%
  all_leisuredata <- all_targetdata3 %>%
  filter(industry_code %in% c(target_sicindustry_codes,target_naics_industry_codes))%>% 
  
  group_by(area_fips, year, qtr, time, industry_title, source) %>% 
  # group_by(area_fips, year, qtr, source) %>% 
  # summarize(leisure = sum(qtrly_estabs_count)) 
  summarize(across(vars, sum)) %>% 
  ungroup()


```
```{r color_line_graphs}

#Industry_Title=Retail Trade Division, Industry_Code= SIC_0G
#Industry_Title=SIC 53 General Merchandise Stores, Industry_Code=SIC_0G53
#Industry_Title=SIC 58 Eating and Drinking Places, Industry_Code=  SIC_0G58
#Industry_Title=SIC 70 Hotels and Other Lodging Places, Industry_Code= SIC_0I70
#Industry_Title=SIC 79 Amusement and Recreation Services, Industry_Code= SIC_0I79	
#Industry_Title=SIC 20 Food and Kindred Products, Industry_Code=SIC_0D20
#Industry_Title=SIC 23 Apparel and Other Textile Products, Industry_Code=SIC_0D23
#Industry_Title=SIC 56 Apparel and Accessory Stores, Industry_Code= SIC_0G56
#Industry_Title=SIC 59 Miscellaneous Retail, Industry_Code=SIC_0G59
#Industry_Title=SIC 70 Hotels and Other Lodging Places, Industry_Code=SIC_0I70


#Industry_Title=Accommodation and food services, Industry_Code=72


vars <-c("qtrly_estabs_count","month1_emplvl","month2_emplvl","month3_emplvl","avg_wkly_wage")

filter(all_leisuredata3, area_fips == "12087") %>% 
ggplot() +
  geom_col(aes(year,qtrly_estabs_count, color = source))

 

filter(all_leisuredata, area_fips == "12087") %>% 
ggplot() +
  geom_line(aes(time,month1_emplvl, color = source))
  
```

```{r facetted_line_graphs}
#Leisure_Hospitality=1026

#Quarterly Establish Count

# filter(all_leisuredata, area_fips %in% florida_fips,industry_code %in% c(target_sicindustry_codes,Leisure_Hospitality)) %>% 
# ggplot() +
#   geom_col(aes(year,qtrly_estabs_count)) +
#   facet_wrap(~ source)

filter(all_leisuredata3, area_fips=="12087") %>% 
ggplot() +
  geom_col(aes(year,qtrly_estabs_count)) +
  facet_wrap(~ source)

filter(all_targetdata2, area_fips %in% texas_fips |industry_code %in% target_sicindustry_codes) %>% 
ggplot() 
  geom_line(aes(year, qtrly_estabs_count)) +
  facet_wrap(~ source)

# Average Weekly Wage

Leisure_Hospitality <- c(1026,72)
# NAIC
#Employment level for the first month of a given quarter
# filter(all_leisuredata3, area_fips==12087) %>% 
# Louisiana 22045- "Iberia";22019	LA	Calcasieu
# Texas 48167	TX	Galveston, 48469	TX	Victoria
#Monroe County 12087

#Employment level for the first month of a given quarter

target_naic_industrycodes<-c('72','1026')
filter(all_leisuredata3, area_fips==12087) %>% 
ggplot() +
  geom_line(aes(year, month1_emplvl, color=source), lwd = 1.25) +
  labs(title = "Employment Level in Monroe County",
         y = "First Month in any given Quater",
         x = "") +
    facet_wrap(~ industry_title, scales = "free")

#Employment level for the first month of a given quarter, Q2

filter(all_leisuredata3, area_fips==12087) %>% 
ggplot() +
  geom_line(aes(time, month3_emplvl, color=source), lwd = 1.25) +
  labs(title = "Employment Level in Monroe County",
         y = "Third Month in any given quater",
         x = "") +
  
    facet_wrap(~ industry_title, scales = "free")


#Employment level for the first month of a given quarter, Q1
# Florida
# filter(all_leisuredata3, area_fips==12087) %>% 
# Louisiana 22045- "Iberia"
filter(all_leisuredata3, area_fips==12087) %>%   
ggplot() +
  geom_line(aes(year, month3_emplvl, color=source), lwd = 1.25) +
  labs(title = "Employment Level in Monroe County",
         y = "Third Month in any given quater",
         x = "") +
    facet_wrap(~ industry_title, scales = "free")
# Average Weekly Wage

filter(all_leisuredata3, area_fips==12087,qtr==1) %>% 
ggplot() +
  geom_line(aes(year, avg_wkly_wage, color=source), lwd = 1.25) +
  labs(title = "Average Weekly Wage for Q1",
         y = "Average weekly wage ",
         x = "") +
    facet_wrap(~ industry_title, scales = "free")

filter(all_leisuredata3, area_fips==12087,qtr==2) %>% 
ggplot() +
  geom_line(aes(year, avg_wkly_wage, color=source), lwd = 1.25) +
  labs(title = "Average Weekly Wage for Q2",
         y = "Average weekly wage ",
         x = "") +
    facet_wrap(~ industry_title, scales = "free")

filter(all_leisuredata3, area_fips==12087,qtr==3) %>% 
ggplot() +
  geom_line(aes(year, avg_wkly_wage, color=source), lwd = 1.25) +
  labs(title = "Average Weekly Wage for Q3",
         y = "Average weekly wage ",
         x = "") +
    facet_wrap(~ industry_title, scales = "free")

filter(all_leisuredata3, area_fips==12087,qtr==4) %>% 
ggplot() +
  geom_line(aes(year, avg_wkly_wage, color=source), lwd = 1.25) +
  labs(title = "Average Weekly Wage for Q4",
         y = "Average weekly wage ",
         x = "") +
    facet_wrap(~ industry_title, scales = "free")


## SIC DATA 

# filter(all_targetdata, area_fips==12087 & industry_code %in% target_sicindustry_codes) %>% 
# ggplot() +
#   geom_line(aes(year, month1_emplvl, color=source), lwd = 1.25) +
#   labs(title = "Employment Level in Texas",
#          y = "First Month in Q1",
#          x = "") +
#     facet_wrap(~ industry_title, scales = "free")



```


And, of course, both at the same time.  Here we color by data source and facet by FIPS

```{r facetted_fips_line_graphs}
# View all FIPS for target area (in Florida Fips)
# filter(all_leisuredata3, area_fips %in% florida_fips) %>% 

  filter(all_leisuredata3, area_fips==12087) %>% 
ggplot() +
  geom_line(aes(year, qtrly_estabs_count, color=source), lwd = 1.25) +
  labs(title = "Trend in coastal work places",
         y = "Number of Establishments",
         x = "") +
    facet_wrap(~ industry_title, scales = "free")
    # facet_wrap(~ area_fips, scales = "free")

 filter(all_leisuredata3, area_fips==12087) %>% 
ggplot() +
  geom_line(aes(year,avg_wkly_wage, color=source), lwd = 1.25) +
  labs(title = "Trend in coastal work places",
         y = "Average Weekly Wage, $",
         x = "") +
    facet_wrap(~ industry_title, scales = "free")
    # facet_wrap(~ area_fips, scales = "free")


```
```{r new_plot}
# targethurdat2 <- st_drop_geometry(targethurdat1)
targethurdat150 <-st_drop_geometry(targethurdat_150)

geom_sf(data = county_pop, aes(fill = totpop))
plot(st_geometry(county_pop))+
plot(st_geometry(targethurdat1))+

filter(all_leisuredata, area_fips == '12005' ) %>% 
ggplot() +
  geom_line(aes(time,avg_wkly_wage, color=source), lwd=1.25) +
     labs(title = "Trend in coastal work places",
         y = "Average Weekly Wage, $",
         x = "") +
  # geom_vline(filter(targethurdat1,fips=='12029'),aes(xintercept=time))
 facet_wrap(~ industry_title, scales = "free")

vertical_lines <- filter(targethurdat150, fips=="22089")
# Galveston 48167
vertical_lines <- filter(targethurdat150, fips=="48167")
#Monroe County, Florida 12087
vertical_lines <- filter(targethurdat2, fips=="12087")



ggplot() + 
  # filter(all_leisuredata,area_fips == '12005'& (industry_title== "Retail Trade Division" | 
  #                                                      industry_title== "Accommodation and food services"))) +
  
  geom_line(data = filter(all_leisuredata,area_fips == '48167' & industry_title == "Retail Trade Division"),
            aes(x=time, y=qtrly_estabs_count), color = "red")+
  # geom_line(data = filter(all_leisuredata,area_fips == '12005'& industry_title == "Accommodation and food services"),
    geom_line(data = filter(all_leisuredata,area_fips == '48167'& industry_title == "Retail trade"),
            aes(x=time, y=qtrly_estabs_count), color = "green")+
  geom_vline(aes(xintercept = as.Date(DateTime), color = ss),vertical_lines)+
  labs(title = "Galveston,Texas",
       subtitle = "Industry Title: Retail Trade",
       x = "Year",
       y = "Quaterly Establishment Count")

### FOOD 

ggplot() + 
  # filter(all_leisuredata,area_fips == '12005'& (industry_title== "Retail Trade Division" | 
  #                                                      industry_title== "Accommodation and food services"))) +
  
  geom_line(data = filter(all_leisuredata,area_fips == '48167' & industry_title == "SIC 54 Food Stores"),
            aes(x=time, y=qtrly_estabs_count), color = "red")+
  # geom_line(data = filter(all_leisuredata,area_fips == '12005'& industry_title == "Accommodation and food services"),
    geom_line(data = filter(all_leisuredata,area_fips == '48167'& industry_title == "Accommodation and food services"),
            aes(x=time, y=qtrly_estabs_count), color = "green")+
  geom_vline(aes(xintercept = as.Date(DateTime), color = ss),vertical_lines)+
  labs(title = "Galveston,Texas",
       subtitle = "Industry Title: SIC 54 Food Stores & NAICS Accommodation and food services",
       x = "Year",
       y = "Quaterly Establishment Count")
### Wholesale Trade
ggplot() + 
  geom_line(data = filter(all_leisuredata,area_fips == '48167' & industry_title == "SIC 51 Wholesale Trade Nondurable Goods"),
            aes(x=time, y=qtrly_estabs_count), color = "red")+
  # geom_line(data = filter(all_leisuredata,area_fips == '12005'& industry_title == "Accommodation and food services"),
    geom_line(data = filter(all_leisuredata,area_fips == '48167'& industry_title == "Wholesale trade"),
            aes(x=time, y=qtrly_estabs_count), color = "green")+
  geom_vline(aes(xintercept = as.Date(DateTime), color = ss),vertical_lines)+
 labs(title = "Galveston,Texas",
       subtitle = "Industry Title: SIC 51 Whole Sale Trade Nondurable Goods & NAICS Wholesale Trade",
       x = "Year",
       y = "Quaterly Establishment Count")
### Wholesale Trade

## Manufacturing
ggplot() + 
  geom_line(data = filter(all_leisuredata,area_fips == '48167' & industry_title == "SIC 39 Miscellaneous Manufacturing Industries"),
            aes(x=time, y=qtrly_estabs_count), color = "red")+
  # geom_line(data = filter(all_leisuredata,area_fips == '12005'& industry_title == "Accommodation and food services"),
    geom_line(data = filter(all_leisuredata,area_fips == '48167'& industry_title == "Manufacturing"),
            aes(x=time, y=qtrly_estabs_count), color = "green")+
  geom_vline(aes(xintercept = as.Date(DateTime), color = ss),vertical_lines)+
  labs(title = "Galveston,Texas",
       subtitle = "Industry Title: NAICS Manufacturing",
       x = "Year",
       y = "Quaterly Establishment Count")
## Leisure and Recreation Services
ggplot() + 
  geom_line(data = filter (all_leisuredata, area_fips == '48167' & industry_title == "SIC 79 Amusement and Recreation Services"),
            aes(x=time, y=qtrly_estabs_count), color = "red")+
  # geom_line(data = filter(all_leisuredata,area_fips == '12005'& industry_title == "Accommodation and food services"),
    geom_line(data = filter(all_leisuredata,area_fips == '48167'& industry_title == "Leisure and hospitality"),
            aes(x=time, y=qtrly_estabs_count), color = "green")+
  geom_vline(aes(xintercept = as.Date(DateTime), color = ss),vertical_lines)+
 labs(title = "Galveston,Texas",
       subtitle = "Industry Title: SIC 79 Amusement and Recreation Services & Leisure and hospitality",
       x = "Year",
       y = "Quaterly Establishment Count")

### BUSINESS SERVICES
ggplot() + 
  geom_line(data = filter (all_leisuredata, area_fips == '48167' & industry_title == "SIC 73 Business Services"),
            aes(x=time, y=qtrly_estabs_count), color = "red")+
    geom_line(data = filter(all_leisuredata,area_fips == '48167'& industry_title == "Professional and business services"),
            aes(x=time, y=qtrly_estabs_count), color = "green")+
  geom_vline(aes(xintercept = as.Date(DateTime), color = ss),vertical_lines)+
 labs(title = "Galveston,Texas",
       subtitle = "Industry Title: SIC 73 Business Services
 & NAICS Professional and business services",
       x = "Year",
       y = "Quaterly Establishment Count")

# MONROE COUNTY
# ggp <- ggplot(filter(all_leisuredata, area_fips==12029),aes(time,avg_wkly_wage,color=source))+
#   geom_line()
# ggp
# 
# dates_vline <- as.Date(c(1975:2020))
# dates_vline <-which(targethurdat1$Time %in% dates_vline)
# 
# ggp+
#   geom_vline(xintercept=as.numeric(targethurdat1$Time[dates_vline]),
# col="black", lwd = 2.00)

  
# filter( all_leisuredata, area_fips==12029) %>% 
#   ggplot() +
#   geom_line(aes(time,avg_wkly_wage, color=source), lwd = 1.25) +
#   # filter(hurdat2,fips==12087)
#   # geom_vline(aes(xintercept=DateTime)))
#   # filter(targethurdat1, fips==12029) %>%
#   # geom_vline(aes(xintercept = "Time", linetype="dotted",
#   #                 color = "blue", size=1.5)) +
#   ggplot() +
#   geom_vline(filter(targethurdat1, fips==12029),xintercept = Time) +
#   labs(title = "Trend in coastal work places",
#          y = "Number of Establishments",
#          x = "") +
#     facet_wrap(~ industry_title, scales = "free")
#     # facet_wrap(~ area_fips, scales = "free")
#   
#  filter(all_leisuredata3, area_fips==12087) %>% 
# ggplot() +
#   geom_line(aes(time,avg_wkly_wage, color=source), lwd = 1.25) +
#    labs(title = "Trend in coastal work places",
#          y = "Average Weekly Wage, $",
#          x = "") +
#     facet_wrap(~ industry_title, scales = "free")
#     # facet_wrap(~ area_fips, scales = "free")
```

```{r avg_wkly_wage}

ggplot() + 
 
  geom_line(data = filter(all_leisuredata,area_fips == '48167' & industry_title == "Retail Trade Division"),
            aes(x=time, y=avg_wkly_wage), color = "red")+
  # geom_line(data = filter(all_leisuredata,area_fips == '12005'& industry_title == "Accommodation and food services"),
    geom_line(data = filter(all_leisuredata,area_fips == '48167'& industry_title == "Retail trade"),
            aes(x=time, y=avg_wkly_wage), color = "green")+
  geom_vline(aes(xintercept = as.Date(DateTime), color = ss),vertical_lines)+
  labs(title = "Galveston,Texas",
       subtitle = "Industry Title: Retail Trade",
       x = "Year",
       y = "Average Weekly Wage")

### FOOD 

ggplot() + 
  # filter(all_leisuredata,area_fips == '12005'& (industry_title== "Retail Trade Division" | 
  #                                                      industry_title== "Accommodation and food services"))) +
  
  geom_line(data = filter(all_leisuredata,area_fips == '48167' & industry_title == "SIC 54 Food Stores"),
            aes(x=time, y=avg_wkly_wage), color = "red")+
  # geom_line(data = filter(all_leisuredata,area_fips == '12005'& industry_title == "Accommodation and food services"),
    geom_line(data = filter(all_leisuredata,area_fips == '48167'& industry_title == "Accommodation and food services"),
            aes(x=time, y=avg_wkly_wage), color = "green")+
  geom_vline(aes(xintercept = as.Date(DateTime), color = ss),vertical_lines)+
  labs(title = "Galveston,Texas",
       subtitle = "Industry Title: SIC 54 Food Stores & NAICS Accommodation and food services",
       x = "Year",
       y = "Average Weekly Wage")
### Wholesale Trade
ggplot() + 
  geom_line(data = filter(all_leisuredata,area_fips == '48167' & industry_title == "SIC 51 Wholesale Trade Nondurable Goods"),
            aes(x=time, y=avg_wkly_wage), color = "red")+
  # geom_line(data = filter(all_leisuredata,area_fips == '12005'& industry_title == "Accommodation and food services"),
    geom_line(data = filter(all_leisuredata,area_fips == '48167'& industry_title == "Wholesale trade"),
            aes(x=time, y=avg_wkly_wage), color = "green")+
  geom_vline(aes(xintercept = as.Date(DateTime), color = ss),vertical_lines)+
 labs(title = "Galveston,Texas",
       subtitle = "Industry Title: SIC 51 Whole Sale Trade Nondurable Goods & NAICS Wholesale Trade",
       x = "Year",
       y = "Average Weekly Wage")
### Wholesale Trade

## Manufacturing
ggplot() + 
  geom_line(data = filter(all_leisuredata,area_fips == '48167' & industry_title == "SIC 39 Miscellaneous Manufacturing Industries"),
            aes(x=time, y=avg_wkly_wage), color = "red")+
  # geom_line(data = filter(all_leisuredata,area_fips == '12005'& industry_title == "Accommodation and food services"),
    geom_line(data = filter(all_leisuredata,area_fips == '48167'& industry_title == "Manufacturing"),
            aes(x=time, y=avg_wkly_wage), color = "green")+
  geom_vline(aes(xintercept = as.Date(DateTime), color = ss),vertical_lines)+
  labs(title = "Galveston,Texas",
       subtitle = "Industry Title: NAICS Manufacturing",
       x = "Year",
       y = "Average Weekly Wage")
## Leisure and Recreation Services
ggplot() + 
  geom_line(data = filter (all_leisuredata, area_fips == '48167' & industry_title == "SIC 79 Amusement and Recreation Services"),
            aes(x=time, y=avg_wkly_wage), color = "red")+
  # geom_line(data = filter(all_leisuredata,area_fips == '12005'& industry_title == "Accommodation and food services"),
    geom_line(data = filter(all_leisuredata,area_fips == '48167'& industry_title == "Leisure and hospitality"),
            aes(x=time, y=avg_wkly_wage), color = "green")+
  geom_vline(aes(xintercept = as.Date(DateTime), color = ss),vertical_lines)+
 labs(title = "Galveston,Texas",
       subtitle = "Industry Title: SIC 79 Amusement and Recreation Services & Leisure and hospitality",
       x = "Year",
       y = "Average Weekly Wage")

### BUSINESS SERVICES
ggplot() + 
  geom_line(data = filter (all_leisuredata, area_fips == '48167' & industry_title == "SIC 73 Business Services"),
            aes(x=time, y=avg_wkly_wage), color = "red")+
    geom_line(data = filter(all_leisuredata,area_fips == '48167'& industry_title == "Professional and business services"),
            aes(x=time, y=avg_wkly_wage), color = "green")+
  geom_vline(aes(xintercept = as.Date(DateTime), color = ss),vertical_lines)+
 labs(title = "Galveston,Texas",
       subtitle = "Industry Title: SIC 73 Business Services
 & NAICS Professional and business services",
       x = "Year",
       y = "Average Weekly Wage")

```

